background #0e1513
foreground #dee4e1
cursor #dee4e1
cursor_text_color #0e1513
selection_background #84d5c4
selection_foreground #0e1513
url_color #abcae4
active_tab_foreground #0e1513
active_tab_background #84d5c4
inactive_tab_foreground #dee4e1
inactive_tab_background #1b211f
color0 #0e1513
color1 #ffb4ab
color2 #b1ccc4
color3 #abcae4
color4 #84d5c4
color5 #3f4946
color6 #005045
color7 #dee4e1
color8 #1b211f
color9 #ffb4ab
color10 #b1ccc4
color11 #abcae4
color12 #84d5c4
color13 #3f4946
color14 #005045
color15 #dee4e1
