background #101418
foreground #e0e2e8
cursor #e0e2e8
cursor_text_color #101418
selection_background #99ccfa
selection_foreground #101418
url_color #d2bfe7
active_tab_foreground #101418
active_tab_background #99ccfa
inactive_tab_foreground #e0e2e8
inactive_tab_background #1c2024
color0 #101418
color1 #ffb4ab
color2 #b8c8da
color3 #d2bfe7
color4 #99ccfa
color5 #42474e
color6 #094b72
color7 #e0e2e8
color8 #1c2024
color9 #ffb4ab
color10 #b8c8da
color11 #d2bfe7
color12 #99ccfa
color13 #42474e
color14 #094b72
color15 #e0e2e8
