# --- General ---
keep-open=yes
save-position-on-quit=yes
autofit-larger=90%x90%

# --- UI ---
osc=yes
osd-bar=no
border=no

# --- Video / Wayland ---
vo=gpu-next
gpu-context=waylandvk
gpu-api=vulkan

# --- Hardware Decoding ---
hwdec=vaapi:decompose
hwdec-codecs=all

# --- Quality ---
scale=bilinear
cscale=bilinear
dscale=bilinear
correct-downscaling=no
linear-downscaling=no
dither-depth=no

# --- Screenshots ---
screenshot-format=png
screenshot-directory=~/Pictures/Screenshots

# --- Thumbfast Worker Profile ---
[thumbfast]
network=no
audio=no
sub=no
video=no
hwdec=no
profile=fast
